### ISSUE TITLE
TypeError: io.listen is not a function

### ISSUE THREAD

**Issue by JacksonSparkle** [cracker0dks/basicwebrtc#14]
I cloned the repo and get this error if I want to run the server for the first time.

TypeError: io.listen is not a function
    at Object.<anonymous> (/var/basicwebrtc/server.js:31:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by cracker0dks** [comment]
hey, what node version are you on? Did you run `npm i` without problems? Can you try to reinstall npm packages with `npm ci` and try again ?

**Comment by JacksonSparkle** [comment]
I tried the new version, but still get the error.
npm i and npm ci doesn't show an error.
> audited 80 packages in 1.555s
> found 0 vulnerabilities
I have node version v10.23.0 running on a debian machine. My friend tried it on a windows machine with the latest lts version and got the same error

**Comment by cracker0dks** [comment]
odd, I tested with Node Versions on Windows:  v15.3.0 (Newest), v14.15.1 (LTS), v13.14.0, v12.18.0 and also version 10.23.0 without this problem. I also defined the package version of socketIO and express for node. Can you please pull the current version and do `npm ci` again? Then post the (new) error msg again pls. Thanks

**Comment by JacksonSparkle** [comment]
Now it's working without any errors, thanks :D
